CONSULTA_EXTRAE_PENDDIENTES = """SELECT  
                            DISTINCT TOP 20
                            A.CDAMOSTRA,
							A.NRCONTROLE1,
							A.NRCONTROLE2,
							A.NRCONTROLE3,
							A.FLATIVO,
                            dbo.numero(A.CDAMOSTRA,0) as NUMMUESTRA,--NUMERO DE MUESTRA
                            P.NMUDPROCESSO02 +';'+P.NMUDPROCESSO05 AS TOEMAIL, --EMAIL
							CE.EMAIL AS CCEMAIL, --CONTATO REPRESENTANTE (CEIMIC)
                            P.IDPROCESSO, --ASUNTO
							E.CDEMPRESA,
							E.IDAUXEMPRESA,
							E.RAZAOSOCIAL,
							E.NMFANTASIA,
							IA.VLINFO as CODIGO_PRODDUCTOR,
							A.CHAVEPUBLICACAO


                            FROM AMOSTRA A
                            INNER JOIN HISTSITAMOSTRA HSIT ON HSIT.CDAMOSTRA=A.CDAMOSTRA AND HSIT.CDSITAMOSTRA=4--PUBLICADO
                            INNER JOIN DOCUMENTOSAMOSTRA DA ON DA.CDAMOSTRA=A.CDAMOSTRA AND DA.FLATIVO='S'
                            INNER JOIN TIPOAMOSTRA TA ON TA.CDTIPOAMOSTRA=DA.CDTIPOARQUIVO and TA.CDTIPOAMOSTRA IN (2)--TIPO 5, TIENE INFORME
                            INNER JOIN UNIDADE U ON U.CDUNIDADE=A.CDUNIDADE
                            INNER JOIN AMOSTRASITENSPRO AITP ON AITP.CDAMOSTRA=A.CDAMOSTRA
                            INNER JOIN PROCESSO P ON P.CDPROCESSO=AITP.CDPROCESSO
							--------
							INNER JOIN EMPRESA E ON E.CDEMPRESA=A.CDEMPRESASOL
							--PARA EXTRAER EL CONTACO REPRESENTANTE
							INNER JOIN CONTATOSEMP CE ON CE.CDCONTATO=P.CDCONTATOREP
							--PARRA CODDIGO DE PRODUCTOR
							INNER JOIN INFOAMOSTRA IA ON IA.CDAMOSTRA	=A.CDAMOSTRA
							INNER JOIN INFO INF ON INF.CDINFO=IA.CDINFO AND IA.CDINFO=682
                            WHERE 
                            A.DTPUBLICACAO>='2025-05-27 00:49:08.000'--MAYOR 
                            AND A.CDCLASSEAMOSTRA=1
                            AND A.FLATIVO='S'
                            AND U.CDUNIDADE in (81,85)--FILTRO FOOD PERU (SOLES,DDOLARES)--FILTRO OBLIGATORIO
                            --AND U.CDUNIDADE IN(10)--TEMPORAL
                           -- AND (P.NMUDPROCESSO02 <>'' AND P.NMUDPROCESSO05 <>'')--TEMPORAL DESPUES BORRAR
							--PARA EMPRESA
							AND E.FLATIVO='S'--EMPRESA ACTIVA
                            ORDER BY E.RAZAOSOCIAL ASC
							"""

INSERTA_PROCESADOS = """INSERT INTO NOTIFICACIONINFORMESPERFOOD
(CDAMOSTRA, NRCONTROLE1, NRCONTROLE2, NRCONTROLE3, ESTADO, DTENVIO, TOEMAIL, CCEMAIL, BCCEMAIL, CUERPO, ASUNTO)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""" 

GET_PROCESADOS="""SELECT * FROM NOTIFICACIONINFORMESPERFOOD"""

CONSULTA_TRAZAS="""SELECT 
                    a.CDAMOSTRA,
                    VS.NMVS as TRAZA,
                    VSA.INFO10 as VALOR
                    FROM AMOSTRA A
                    INNER JOIN VSAMOSTRA VSA ON VSA.CDAMOSTRA=A.CDAMOSTRA
                    INNER JOIN VARSAIDA VS ON VS.CDVS=VSA.CDVS
                    WHERE A.CDAMOSTRA IN ({cod_muestras}) 
                    AND A.FLATIVO='S'
                    AND A.CDCLASSEAMOSTRA=1
                    AND VSA.VLVS ='ND'
                    AND VSA.INFO10 IS NOT NULL"""
